added Glowdust Layer feature to Glowstone canyon biome
nekomaster1000/Infernal-Expansion pull request #113
Opened 2021-05-05 16:33 UTC by TelepathicGrunt

title says it all

2021-05-05 18:01 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/init/IEFeatures.java
> +import com.nekomaster1000.infernalexp.world.gen.features.*;
Swan is gonna freak about this one

2021-05-05 18:46 UTC, Dariensg requested changes

2021-05-05 18:46 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/init/IEFeatures.java
> +import com.nekomaster1000.infernalexp.world.gen.features.*;
Don't use Wildcards -Swan Probably

2021-05-05 18:46 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/world/gen/features/GlowLayerFeature.java
> +                if(x == 0 && z == 0) continue;
```suggestion
                if (x == 0 && z == 0) continue;
```

2021-05-05 18:46 UTC, SwanX1 commented on src/main/java/com/nekomaster1000/infernalexp/init/IEFeatures.java
> +import com.nekomaster1000.infernalexp.world.gen.features.*;
definitely*

2021-05-06 15:02 UTC, Dariensg approved these changes

2021-05-06 15:02 UTC, Dariensg commented
LGTM

2021-05-06 15:02 UTC, merged