optimized sinkhole, fixed sinkhole and ravine from making floating lava
nekomaster1000/Infernal-Expansion pull request #115
Opened 2021-05-05 17:25 UTC by TelepathicGrunt

The solution was to make them place lava if below sealevel. Should help clean up those carvers/feature

Also, try to use BlockPos.Mutable when iterating over a large amount of space as calling .add every time will create a new blockpos object. It can get excessive to the garbage collector if you create millions of blockpos for a feature

2021-05-05 17:33 UTC, caelwarner approved these changes
Thanks for the advice with BlockPos.Mutable!

2021-05-05 18:50 UTC, Dariensg requested changes

2021-05-05 18:50 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/world/gen/features/SinkHoleFeature.java
> +        else {
```suggestion
        } else {
```

2021-05-05 18:50 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/world/gen/features/SinkHoleFeature.java
> +            else {
```suggestion
            } else {
```

2021-05-06 12:56 UTC, Dariensg commented
LGTM

2021-05-06 15:02 UTC, Dariensg approved these changes

2021-05-06 15:03 UTC, merged