Added nether biome whitelist/blacklist config option
nekomaster1000/Infernal-Expansion pull request #155
Opened 2021-07-13 23:31 UTC by caelwarner

- Allows players to create a whitelist or blacklist of biomes that spawn in the nether
- Added WorldGenerationScreen GUI

2021-07-13 23:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/infernalexp/Infernal-Expansion?pullRequest=155) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/infernalexp/Infernal-Expansion?pullRequest=155) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/infernalexp/Infernal-Expansion?pullRequest=155) it.</sub>

2021-07-13 23:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/infernalexp/Infernal-Expansion?pullRequest=155) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/infernalexp/Infernal-Expansion?pullRequest=155) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/infernalexp/Infernal-Expansion?pullRequest=155) it.</sub>

2021-07-14 01:12 UTC, Dariensg commented
LGTM, we need to make sure that all the other lang files are also updated to reflect this. I can take care of that in a matter of minutes once this is merged if you would like.

2021-07-14 01:14 UTC, caelwarner commented
I say lets wait until we have actually finalized everything and are ready to release the beta.

2021-07-14 19:02 UTC, SwanX1 requested changes
minor changes

2021-07-14 19:02 UTC, SwanX1 commented on src/main/java/com/nekomaster1000/infernalexp/world/dimension/ModNetherBiomeCollector.java
> +                    if ((whitelistEnabled && whitelistOrBlacklist.contains(entry.getKey().getLocation().toString())) || (!whitelistEnabled && !whitelistOrBlacklist.contains(entry.getKey().getLocation
would've preferred some line breaks/indentation here

2021-07-14 19:02 UTC, SwanX1 commented on src/main/java/com/nekomaster1000/infernalexp/config/CommonConfig.java
> +            .translation(InfernalExpansion.MOD_ID + ".config.tooltip.biomesWhitelistEnabled")
```suggestion
            .comment("Determines if the biome list below should act as a whitelist, or, when disabled, a blacklist.")
            .comment("CHANGING THIS REQUIRES A GAME RESTART.")
            .translation(InfernalExpansion.MOD_ID + ".config.tooltip.biomesWhitelistEnabled")
```

2021-07-14 19:02 UTC, SwanX1 commented on src/main/java/com/nekomaster1000/infernalexp/config/CommonConfig.java
> +    final ForgeConfigSpec.BooleanValue biomesWhitelistEnabled;
`biomeListIsWhitelist` would be more appropriate and self-explanatory.

2021-07-14 19:02 UTC, SwanX1 commented on src/main/java/com/nekomaster1000/infernalexp/config/CommonConfig.java
> +    final ForgeConfigSpec.ConfigValue<String> biomesWhitelistOrBlacklist;
in `ForgeConfigSpec.ConfigValue<T>`, `T` can be `List<String>`

2021-07-14 19:02 UTC, SwanX1 commented on src/main/java/com/nekomaster1000/infernalexp/config/CommonConfig.java
> +    final ForgeConfigSpec.ConfigValue<String> biomesWhitelistOrBlacklist;
If `biomesWhitelistEnabled` is renamed, rename this to `biomesList`

2021-07-14 19:05 UTC, caelwarner commented on src/main/java/com/nekomaster1000/infernalexp/config/CommonConfig.java
> +    final ForgeConfigSpec.ConfigValue<String> biomesWhitelistOrBlacklist;
Does making it `List<String>` parse it automatically?

2021-07-14 19:08 UTC, SwanX1 commented on src/main/java/com/nekomaster1000/infernalexp/config/CommonConfig.java
> +    final ForgeConfigSpec.ConfigValue<String> biomesWhitelistOrBlacklist;
yes

2021-07-14 20:38 UTC, caelwarner commented on src/main/java/com/nekomaster1000/infernalexp/config/CommonConfig.java
> +    final ForgeConfigSpec.ConfigValue<String> biomesWhitelistOrBlacklist;
honestly, keeping it as a string is just easier for me. If I change it to be a list then I have to write code to parse it for the GUI

2021-07-14 20:55 UTC, SwanX1 approved these changes

2021-07-14 20:55 UTC, SwanX1 commented
Gonna merge this one

2021-07-14 20:57 UTC, merged