Added Shroomloin Variations and Warpbeetle Variation. Still haven't a…
nekomaster1000/Infernal-Expansion pull request #157
Opened 2021-07-14 22:51 UTC by 0rc1nus

…dded the shaking feature yet.

2021-07-14 22:57 UTC, SwanX1 requested changes, later dismissed

2021-07-14 22:57 UTC, SwanX1 commented on src/main/java/com/nekomaster1000/infernalexp/entities/WarpbeetleEntity.java
> +    public boolean getVariant() {
Should be renamed to `isChorus`

2021-07-14 22:57 UTC, SwanX1 commented on src/main/java/com/nekomaster1000/infernalexp/entities/WarpbeetleEntity.java
> +    public void setVariant(boolean variant) {
Should be renamed to `setChorus`

2021-07-14 22:57 UTC, SwanX1 commented on src/main/java/com/nekomaster1000/infernalexp/events/MiscEvents.java
>                  }
Checking for the fungus type first would be more performant.

2021-07-14 22:59 UTC, SwanX1 commented
I'm going to wait until the shaking feature is implemented before merging.

2021-07-15 00:48 UTC, Dariensg requested changes

2021-07-15 00:48 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/events/MiscEvents.java
> +                        || state.equals(Blocks.NETHER_WART_BLOCK.getDefaultState())) {
Please turn all of these groups of blocks into tags and use state.getBlock().isIn(Tag)

2021-07-15 01:58 UTC, Dariensg requested changes

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/WarpbeetleEntity.java
> +    private int converstionTicks;
```suggestion
    private int conversionTicks;
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/ShroomloinEntity.java
> +    private int converstionTicks;
```suggestion
    private int conversionTicks;
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/ShroomloinEntity.java
> +        this.converstionTicks = time;
```suggestion
        this.conversionTicks = time;
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/ShroomloinEntity.java
> +                this.converstionTicks = 40;
```suggestion
                this.conversionTicks = 40;
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/ShroomloinEntity.java
> +                this.converstionTicks = 40;
```suggestion
                this.conversionTicks = 40;
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/ShroomloinEntity.java
> +                this.converstionTicks = 40;
```suggestion
                this.conversionTicks = 40;
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/ShroomloinEntity.java
> +                this.converstionTicks = 40;
```suggestion
                this.conversionTicks = 40;
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/ShroomloinEntity.java
> +                this.converstionTicks = 40;
```suggestion
                this.conversionTicks = 40;
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/ShroomloinEntity.java
> +		        this.converstionTicks--;
```suggestion
		        this.conversionTicks--;
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/ShroomloinEntity.java
> +		        if (this.converstionTicks == 0) {
```suggestion
		        if (this.conversionTicks == 0) {
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/ShroomloinEntity.java
> +        compound.putInt("ShroomloinConversionTime", this.converstionTicks);
```suggestion
        compound.putInt("ShroomloinConversionTime", this.conversionTicks);
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/WarpbeetleEntity.java
> +        compound.putInt("WarpbeetleConversionTime", this.converstionTicks);
```suggestion
        compound.putInt("WarpbeetleConversionTime", this.conversionTicks);
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/WarpbeetleEntity.java
> +        this.converstionTicks = time;
```suggestion
        this.conversionTicks = time;
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/WarpbeetleEntity.java
> +            this.converstionTicks = 40;
```suggestion
            this.conversionTicks = 40;
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/WarpbeetleEntity.java
> +            this.converstionTicks = 40;
```suggestion
            this.conversionTicks = 40;
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/WarpbeetleEntity.java
> +            if (this.isConverting() && this.converstionTicks > 0) {
```suggestion
            if (this.isConverting() && this.conversionTicks > 0) {
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/WarpbeetleEntity.java
> +                this.converstionTicks--;
```suggestion
                this.conversionTicks--;
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/entities/WarpbeetleEntity.java
> +                if (this.converstionTicks == 0) {
```suggestion
                if (this.conversionTicks == 0) {
```

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/events/MiscEvents.java
> +                    if (state.getBlock().isIn(IETags.Blocks.ANGER_CRIMSON_BLOCKS)) {
Could you please refactor these tags to be ANGER_CRIMSON_SHROOMLOIN_BLOCKS, etc.

2021-07-15 01:58 UTC, Dariensg commented on src/main/java/com/nekomaster1000/infernalexp/init/IETags.java
> +        public static final ITag.INamedTag<Block> ANGER_CRIMSON_BLOCKS = tag("anger_crimson_blocks");
Same as above, please refactor these tags to include "shroomloin"

2021-07-15 02:11 UTC, Dariensg approved these changes

2021-07-15 02:23 UTC, merged