Added Compat World Type
nekomaster1000/Infernal-Expansion pull request #229
Opened 2021-08-03 20:47 UTC by Dariensg

-Added a custom world type to allow for use of our Nether BiomeProvider in TerraForged worlds
-Made sure to hide the World Type unless in Debug World Types
-Added a lang even though TerraForged won't use it for the sake of it looking good if people discover it in the debug menu

2021-08-03 22:58 UTC, caelwarner requested changes

2021-08-03 22:58 UTC, caelwarner commented on src/main/java/org/infernalstudios/infernalexp/world/type/CompatWorldType.java
> +        SimpleRegistry<Dimension> simpleregistry = new SimpleRegistry<>(Registry.DIMENSION_KEY, Lifecycle.stable());
Rename `simpleregistry` to `simpleRegistry`

2021-08-03 23:00 UTC, caelwarner approved these changes
👍

2021-08-04 10:16 UTC, SwanX1 approved these changes

2021-08-04 11:06 UTC, merged