Numerous Balance Changes & Additions
nekomaster1000/Infernal-Expansion pull request #328
Opened 2022-03-06 15:50 UTC by nekomaster1000

- Cured Jerky's Speed II effect now lasts for 15 seconds.
- Raw Hogchops now poison you with 10 seconds of Infection II, while Cooked Hogchops give you 10 seconds of Slowness II (to balance out their incredible hunger restoration)
- Added the Spirit Eye, which gives you 10 seconds of Glowing when you eat it.
- Changed the Tongue Whip to deal 6 points of damage instead of 3, in addition to making it charge faster by 7 ticks.
- Added the Kinetic Tongue Whip, a Mining Master compatibility weapon. Deals 8 points of damage.
- Removed bizarro 'Dullthorn_block' texture.
- Updated Dullthorns Block texture palette to be consistent with the current Dullthorns textures.
- Updated the Dullthorns Tip texture so that if the tiling breaks and repeats the top texture, it should still look somewhat good.
- Glowsilk now repairs 2000 Durability at the cost of 5 levels, from a previous 200 Durability at 4 levels cost.
- Updated Glowsilk Bow & Ascus Bomb sprites.
- Reduced Blindsights' Luminance bestowing to 5 seconds from 30.
- Blindsights now give you 10 seconds of Jump Boost II on-hit.
- Blindsight Tongue is now consumable for 5 seconds of Jump Boost II.
- Deleted the Skeletal Piglin Loot table :(
- Blackstone Dwarves now only drop an Apple if killed by the Player.
- Blindsights, Shroomloins and Hoglins drop their loot less often.
- Made Shroomloins far harder to anger, removing most blocks from their anger goals.
- It should no longer rain in the Glowstone Canyon (and Delta Shores.)
- Fixed Infection Overlay displaying incorrectly.

To Do:
Kinetic Tongue Whip needs to utilises Knockback III in addition to being given more durability.

Thank you Ludo for helping catch my mistakes and implementing the Hogchop drop-rate change and Kinetic Tongue Whip rendering!

2022-03-06 15:55 UTC, SwanX1 commented
Should blindsight attacks give you a positive effect?

2022-03-06 15:58 UTC, nekomaster1000 commented
The Tongue Stew and Tongue both give you Jump Boost, so it was added to the Blindsight's attack too. You could argue it's somewhat negative when the Blindsight applies it to you as it could momentarily mess with your spacial awareness if you're jumping to fight it.

2022-03-06 16:15 UTC, SwanX1 requested changes

2022-03-06 16:15 UTC, SwanX1 commented on src/main/java/org/infernalstudios/infernalexp/init/IEItems.java
> +import org.infernalstudios.infernalexp.items.*;
\>:(

2022-03-06 16:15 UTC, SwanX1 commented on src/main/java/org/infernalstudios/infernalexp/init/IEItems.java
> +    public static final RegistryObject<WhipItem> BLINDSIGHT_TONGUE_WHIP = registerItem("blindsight_tongue_whip", () -> new WhipItem(IEItemTiers.BLINDSIGHT_TONGUE, 4.0F, -3.4F, new Item.Properties().g
I thought the damage was balanced, why the change? I mean, you can literally enchant it with sharpness

2022-03-06 16:15 UTC, SwanX1 commented on src/main/java/org/infernalstudios/infernalexp/init/IEItems.java
> +
tooo many empty lines

2022-03-06 16:15 UTC, SwanX1 commented on src/main/java/org/infernalstudios/infernalexp/init/IELootModifiers.java
>              }
```suggestion
            if (context.getRandom().nextDouble() < 0.6 || !InfernalExpansionConfig.MobInteractions.USE_HOGCHOPS.getBoolean()) {
                return generatedLoot;
            }
```

2022-03-06 16:15 UTC, SwanX1 commented on src/main/java/org/infernalstudios/infernalexp/init/IEItems.java
> +    public static final RegistryObject<WhipItem> BLINDSIGHT_TONGUE_WHIP = registerItem("blindsight_tongue_whip", () -> new WhipItem(IEItemTiers.BLINDSIGHT_TONGUE, 4.0F, -3.4F, new Item.Properties().g
Why change the attack damage? I think it was balanced before

2022-03-06 16:15 UTC, SwanX1 commented on src/main/java/org/infernalstudios/infernalexp/init/IEItems.java
> +
Do you really need another method for this?
See my code suggestion above

2022-03-06 16:15 UTC, SwanX1 commented on src/main/java/org/infernalstudios/infernalexp/init/IEItems.java
> +    public static final RegistryObject<WhipItem> KINETIC_TONGUE_WHIP = registerItemConditioned("kinetic_tongue_whip", () -> new WhipItem(IEItemTiers.BLINDSIGHT_TONGUE, 6.0F, -3.4F, new Item.Propertie
```suggestion
    public static final RegistryObject<WhipItem> KINETIC_TONGUE_WHIP = registerItem("kinetic_tongue_whip", () -> new WhipItem(IEItemTiers.BLINDSIGHT_TONGUE, 6.0F, -3.4F, ModList.get().isLoaded("miningmaster") ? new Item.Properties().group(InfernalExpansion.TAB) : new Item.Properties()));
```

2022-03-06 16:15 UTC, SwanX1 commented on src/main/java/org/infernalstudios/infernalexp/init/IEItems.java
> +
~~Skill~~ Formatting issue:
```suggestion
    public static <T extends Item> RegistryObject<T> registerItemConditioned(String name, Supplier<? extends T> itemSupplier, Supplier<? extends T> itemSupplierCompat, String modID) {
        RegistryObject<T> item = ITEMS.register(name, ModList.get().isLoaded(modID) ? itemSupplier : itemSupplierCompat);
        return item;
    }
```

2022-03-06 16:15 UTC, SwanX1 commented on src/main/java/org/infernalstudios/infernalexp/init/IELootModifiers.java
>              }
```suggestion
            if (context.getRandom().nextDouble() < 0.6 || !InfernalExpansionConfig.MobInteractions.USE_HOGCHOPS.getBoolean()) {
                return generatedLoot;
            }
```

2022-03-06 16:15 UTC, SwanX1 commented on src/main/resources/assets/infernalexp/models/item/spirit_eye.json
> +    "layer0": "infernalexp:item/spirit_eye"
lmao what

2022-03-06 16:15 UTC, SwanX1 commented
LGTMn't

2022-03-06 16:27 UTC, nekomaster1000 commented on src/main/java/org/infernalstudios/infernalexp/init/IEItems.java
> +    public static final RegistryObject<WhipItem> BLINDSIGHT_TONGUE_WHIP = registerItem("blindsight_tongue_whip", () -> new WhipItem(IEItemTiers.BLINDSIGHT_TONGUE, 4.0F, -3.4F, new Item.Properties().g
Nobody wanted to use the Whip with it's previous damage output. It's new damage is akin to an Iron Sword, which I feel is appropriate.

2022-05-31 20:55 UTC, Dariensg approved these changes
LGTM

2022-05-31 21:08 UTC, merged